version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: walmart-ads-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: metricsdb
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: metrics_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
